version: 2.4.{build}

branches:
  except:
  - coverity_scan

configuration: Release

environment:
  PROJECT_BASE: "C:/projects/morebin"

platform: x64

before_build:
- cmd: dir C:\Libraries\boost_1_60_0\
- ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
- cmd: dir
- cmd: md build
- cmd: cd build
- cmd: cmake --version
- cmd: cmake -G"Visual Studio 12 2013 Win64" -C"../appveyor.cmake" -H.. -B.

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal

artifacts:
  - path: 'build/googletest/src/googletest-1.7.0-stamp/*.log'
    name: gtest build logs
