version: 2.4.{build}

branches:
  except:
  - coverity_scan

configuration: Release

environment:
  PROJECT_BASE: "C:/projects/morebin"
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

platform: x64

build_script:
  - md build
  - cd build
  - cmake -G"Visual Studio 12 2013 Win64" ..
  - cmake --build . --config Release

test_script:
  - dir Release
  - morebin --version
  - "ctest --build-config Release --output-on-failure"
