version: 1.0.{build}

branches:
  except:
  - coverity_scan

configuration: Release

install:
- ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}"

before_build:
- ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
- cmd: dir
- cmd: md build
- cmd: cd build
- cmd: cmake --version
- cmd: cmake -G "Visual Studio 12 Win64"  ..
- cmd: dir

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal
