version: 1.0.{build}

branches:
  except:
  - coverity_scan

configuration: Release

install:
- nuget install boost

before_build:
- ps: >-
    cd "${env:APPVEYOR_BUILD_FOLDER}"
    md build
    cd build
    cmake --version
    cmake -G "Visual Studio 12 Win64"  ..
    dir

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal
