version: 2.4.{build}

branches:
  except:
  - coverity_scan

configuration: Release

environment:
  PROJECT_BASE: "C:/projects/morebin"
  PATH: "%PROJECT_BASE%/boost_date_time-vc120.1.58.0.0/lib/native/address-model-64/lib;%PROJECT_BASE%/boost_program_options-vc120.1.58.0.0/lib/native/address-model-64/lib;%PROJECT_BASE%/gtest/src/gtest-build/Release;%PROJECT_BASE%/gmock/src/gmock-build/Release;%PATH%"


platform: x64

install:
- ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}"
- ps: nuget install boost_date_time-vc120 -o "${env:APPVEYOR_BUILD_FOLDER}"
- ps: nuget install boost_program_options-vc120 -o "${env:APPVEYOR_BUILD_FOLDER}"

before_build:
- ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
- cmd: dir
- cmd: md build
- cmd: cd build
- cmd: cmake --version
- cmd: cmake -G"Visual Studio 12 Win64" -C"../appveyor.cmake" -H.. -B.

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal

test_script:
 - ctest -C Release --output-on-failure