version: 1.0.{build}

branches:
  except:
  - coverity_scan

configuration: Release

platform: x64

install:
- ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}"
- ps: nuget install boost_date_time-vc120 -o "${env:APPVEYOR_BUILD_FOLDER}"
- ps: nuget install boost_program_options-vc120 -o "${env:APPVEYOR_BUILD_FOLDER}"

before_build:
- ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
- cmd: dir
- cmd: dir boost_date_time.1.58.0.0\lib\native
- cmd: md build
- cmd: cd build
- cmd: cmake --version
- ps: cmake -G "Visual Studio 12 Win64" -C appveyor.cmake ..

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal
