version: 1.0.{build}

branches:
  except:
  - coverity_scan

configuration: Release

platform: x64

install:
- ps: nuget install boost
- ps: nuget install boost_date_time
- ps: nuget install boost_program_options

before_build:
- ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
- cmd: dir boost.1.58.0.0
- cmd: dir boost.1.58.0.0\lib\native
- cmd: md build
- cmd: cd build
- cmd: cmake --version
- ps: cmake -G "Visual Studio 12 Win64"  ..

build:
  project: C:\projects\morebin\build\morebin.sln
  parallel: true
  verbosity: normal
