version: 2.4.{build}

branches:
  except:
  - coverity_scan

configuration: Release

environment:
  PROJECT_BASE: "C:/projects/morebin"
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
  PATH: '%BOOST_LIBRARYDIR%;%PATH%'

platform: x64

build_script:
  - md build
  - cd build
  - cmake -G"Visual Studio 14 2015 Win64" .. -DENABLE_TESTS=ON
  - cmake --build . --config %configuration%

test_script:
  - ctest -VV --build-config %configuration% --output-on-failure
