language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-program-options-dev libboost-date-time-dev

before_script:
  - cmake .

script:
  - make
#  - make package # doesn't work on ubuntu

notifications:
  email:
    on_success: change
    on_failure: always
