language: cpp

compiler:
  - gcc
#  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-program-options-dev libboost-date-time-dev
  - cmake .

script: make

notifications:
  email:
    on_success: change
    on_failure: always
