sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_script:
#ALWAYS analyze a project in its "debug" configuration
  - if [ "$CXX" == "clang++" ];
    then
      scan-build cmake -DCMAKE_BUILD_TYPE=Debug .;
    else
      cmake .;
    fi

script:
#Run the clang static analyzer.
  - if [ "$CXX" == "clang++" ];
    then
      scan-build make;
    else
      make;
    fi
#  - make package # doesn't work on ubuntu

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - clang-3.4
      - libboost-program-options-dev
      - libboost-date-time-dev
