language: cpp

compiler:
  - gcc
#  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq boost-program-options
  - cmake .

script: make

notifications:
  email:
    on_success: change
    on_failure: always