sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_script:
#ALWAYS analyze a project in its "debug" configuration
  - if [ "$CXX" == "clang++" ];
    then
      CC=clang-3.6 CXX=clang++-3.6 scan-build-3.6 cmake -DCMAKE_BUILD_TYPE=Debug .;
    else
      cmake .;
    fi

script:
#Run the clang static analyzer.
  - if [ "$CXX" == "clang++" ];
    then
      CC=clang-3.6 CXX=clang++-3.6 scan-build-3.6 make;
    else
      make;
    fi
  - ctest --output-on-failure;
#  - make package # doesn't work on ubuntu

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
      - libboost-program-options-dev
      - libboost-date-time-dev
