language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-program-options-dev libboost-date-time-dev

before_script:
  - cmake .

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi
#  - make package # doesn't work on ubuntu

notifications:
  email:
    on_success: change
    on_failure: always


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VGO+YMWnF7ya6SoSyLYdOyXbqMFsY4Al22UQ+Wewf2BpoYNrBEUXvDNtdu54KjSmjASuDp4BTF0DD8NtzcOz+LLhkdBT8GfTcInJnxY8uYWIqciIqa1DZAuhp0pLHYfLQ2PBoKgthkMGRKg7VAcBNbXsTpwfcqcxZsX3KtYXFR8="

addons:
  coverity_scan:
    project:
      name: "peterfpeterson/morebin"
      description: "Build submitted via Travis CI"
    notification_email: peterfpeterson@gmail.com
    build_command_prepend: "cmake .; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
