set(BUILD_DIR C:/projects/morebin CACHE PATH "")
set(BOOST_ROOT C:/Libraries/boost_1_60_0/ CACHE_PATH "")
set(BOOST_DIR C:/Libraries/boost_1_60_0/ CACHE_PATH "")
set(BOOST_INCLUDE_DIR C:/Libraries/boost_1_60_0/ CACHE_PATH "")
set(BOOST_LIBRARY_DIR C:/Libraries/boost_1_60_0/lib64-msvc-14.0/ CACHE_PATH "")
